export const LOAD_POSTS_REQUESTED = 'LOAD_POSTS_REQUESTED';
export const LOAD_POSTS_FAILED = 'LOAD_POSTS_FAILED';
export const LOAD_POSTS_SUCCEEDED = 'LOAD_POSTS_SUCCEEDED';
export const LOAD_COMMENTS_REQUESTED = 'LOAD_COMMENTS_REQUESTED';
export const LOAD_COMMENTS_FAILED = 'LOAD_COMMENTS_FAILED';
export const LOAD_COMMENTS_SUCCEEDED = 'LOAD_COMMENTS_SUCCEEDED';
